### ISSUE TITLE
About the "Updating Your Firmware" instructions

### ISSUE THREAD

**Issue by dark-passages** [mwasilew/boxzy#1]
First: Thank you for sharing the BoXZY documentation! 

About the "[Updating Your Firmware](https://github.com/mwasilew/boxzy/blob/master/Upgrading_firmware.md)" instructions:

* After downloading the firmware you mention I find a lot of folders, including more than 1 src folder, I'm guessing we should use ArduinoAVR for BoXZY.

* There are also specific Configuration.h files for specific printers (except BoXZY) and even instructions on how to use the "Repetier-Firmware configuration tool".  With this tool, it should be possible to have the Laser and CNC options working (I hope) but I have no clue what the settings should be to make it work. Is there someone who knows what the content of the Configuration.h file should be?

**Comment by mwasilew** [comment]
I didn't update the firmware and the text in the repository is copied from wayback machine. After I did that, someone uploaded original docs in PDF to github: https://github.com/chappy1978/Boxzy- . Hopefully you can find your answers there.

I'll update the description if I complete the firmware update on my boxzy.

**Comment by mwasilew** [comment]
https://github.com/chappy1978/Boxzy-/blob/main/Updating%20your%20firmware.pdf
My text only version is supposed to cover this document

**Comment by dark-passages** [comment]
Thanks for the fast reply! It looks like that is exactly what I was looking for.
________________________________
